services:
  wireguard:
    image: linuxserver/wireguard:version-v1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./wg0.conf:/config/wg_confs/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmission:
    image: linuxserver/transmission:4.0.5
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #54914
      - HOST_WHITELIST= #optional
    volumes:
      - ./transmission-config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    restart: always
